from datetime import timedelta


REQUEST_STATISTICS_RATE = 5
MAX_USERS_PER_CLIENT = 1450
CLIENT_DISCONNECT_TIMEOUT = 1
PIXELS_TIMEOUT = 10
CANVAS_UPDATE_TIME = 30
MAX_PIXELS_DISTRIBUTION_TIME = timedelta(seconds=10)
